sys: System{
    shape: rectangle
}

us: User {
    shape: person
}

td: Driver {
    shape: person    
}

mn: Manager {
    shape: person
}

sys.uc1: Maintain Account {
    shape: oval
}
sys.uc2: Maintain cargo {
    shape: oval
}

td -> us <- mn

us -- sys.uc1

mn -- sys.uc2